feat: Loom video support
radiovisual/get-video-id pull request #105
Opened 2022-10-22 21:04 UTC by Dheerajkawatra

2023-08-11 21:02 UTC, crhayes commented
@radiovisual Thoughts on this PR? It would be great to have loom support in the library.

2023-08-21 11:24 UTC, radiovisual commented
Look support sounds nice. I can take a closer look at the PR soon

2023-08-22 20:11 UTC, radiovisual requested changes
@Dheerajkawatra Thanks for the contribution! Sorry for the super late review!

2023-08-22 20:11 UTC, radiovisual commented on src/loom.js
> +		= /(https?:\/\/)?(www\.)?loom\.com\/?(.*\/)?([\d)([a-z]{32})\??.*/;
Seems like this RegEx is way to strict which might present problems (false positives, not flexible, etc), so I think you can really simplify this RegEx to make it focus on the specific strings you are looking for, and don't force length limits on the hashed id. something like (this is not tested, so please test it or modify it accordingly):
```suggestion
		= /^https?:\/\/(?:www\.)?loom\.com\/(?:share|embed)\/([\da-zA-Z]+);
```

2023-08-23 18:40 UTC, Dheerajkawatra commented
> @Dheerajkawatra Thanks for the contribution! Sorry for the super late review!

no worries, Thanks for the review @radiovisual . I'll fix asap

2023-11-24 09:13 UTC, radiovisual commented
@Dheerajkawatra are you still interested in this PR? I can pick up the remaining work if you need some help.

2024-02-18 22:28 UTC, radiovisual commented
I will close this stale PR since Loom video support was added via https://github.com/radiovisual/get-video-id/pull/110

2024-02-18 22:28 UTC, closed without merging