Tiktok support
radiovisual/get-video-id pull request #67
Opened 2021-07-14 20:30 UTC by Maxou44

Basic support for tiktok links, it don't support short links yet (see: #66)

2021-07-14 20:32 UTC, Maxou44 commented
I failed, the MR also includes Dailymotion supports

2021-08-31 06:55 UTC, radiovisual requested changes

2021-08-31 06:55 UTC, radiovisual commented on tests/index.test.js
> + *  Not supported yet (requires a fetch):
We should probably add a note about this to the Readme in the `Tiktok` patterns section, to make it more visible which Tiktok patterns this module doesn't support.

2021-09-01 08:09 UTC, radiovisual commented on tests/index.test.js
> + *  Not supported yet (requires a fetch):
I added a note about the unsupported TikTok URL to the Readme via https://github.com/radiovisual/get-video-id/pull/67/commits/6d1a888239a1476d3db86251bbfd5e13c3dd1267.

2021-09-01 08:13 UTC, merged

2021-09-01 16:16 UTC, radiovisual commented
@Maxou44 TikTok support was added in version `3.4.0`. Thanks for your contribution!